let dataEvento = 5
if (dataEvento < 16) {
    console.log ("permitir evento")
} else {
    console.log ("data do evento inválida")
}

let idadeParticipante = 21
if (idadeParticipante > 18) {
    console.log ("Permitir Cadastro")
} else {
    console.log ("Cadastro não Permitido por conta da idade") 
}

let participantesPalestrantes = 80
if (participantesPalestrantes <100) {
    console.log ("Cadastro não permitido pelo acesso excedido")
} else {   
}